version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:80"
    environment:
      - VERSION=${VERSION}
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: webapp
    ports:
      - "5432:5432"
